- tags: [docker]

  block:
    - name: uninstall docker.io if present
      ansible.builtin.apt:
        name: '{{ item }}'
        state: absent
      with_items:
        - docker.io
        - docker-compose

    - name: Add docker gpg key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add docker apt repository
      ansible.builtin.apt_repository:
        repo: 'deb [arch={{ deb_architecture[ansible_architecture] }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable'
        state: present

    - name: install docker-ce
      ansible.builtin.apt:
        name: docker-ce
        state: present
